### ISSUE TITLE
Uncaught Error: Reference.push failed: first argument contains undefined in property 'messages.user._id'

### ISSUE THREAD

**Issue by 4evera1one** [avegrv/react-native-firebase-chat#2]
Uncaught Error: Reference.push failed: first argument contains undefined in property 'messages.user._id'. Gives me this when I put my firebase configurations instead of the default ones.

**Comment by avegrv** [comment]
Thank you for your reply. This project was created for demo usage and it doesn't contain any error handling logic. 
So for your case seems that firebase didn't initialize and for this reason reference of the database is undefined. Check firebase config one more time.

**Comment by avegrv** [comment]
@4evera1one  Thank you for your reply. This project was created for demo usage and it doesn't contain any error handling logic. So for your case seems that firebase didn't initialize and for this reason reference of the database is undefined. Check firebase config one more time.

**Comment by 4evera1one** [comment]
thanks, fixed it!
