### ISSUE TITLE
ERROR: e.toUpperCase is not a function 

### ISSUE THREAD

**Issue by AnatuGreen** [avegrv/react-native-firebase-chat#3]
This error is coming up when you run this on expo and even on the web emulator on snack.
The error come up after typing in my name and clicking the next button. I have checked but could not find the source of the issue;

![image](https://user-images.githubusercontent.com/95270336/150374753-b9439258-8ba2-43c4-ba1a-558a518d4b10.png)

**Comment by avegrv** [comment]
Fixed. But still have problems with expo. I'm waiting for 44 release. Maybe it will help.
Just for now try to start it locally.

`yarn expo start --ios`

**Comment by avegrv** [comment]
Removed snack, waiting till expo update expo-snack to 44 SDK
